name: CI
on:
  pull_request:
jobs:
  test:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - run: go mod download
      - uses: reviewdog/action-setup@v1
      - run: go test -json ./... > out.jsonl
      - name: report test failures
        run: cat out.jsonl | go run ./cmd/gotest2rdjsonl | reviewdog -f rdjsonl -reporter github-pr-review
